/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Application {
  constructor()
  /**
   * Configure the private dev-server endpoint used to run the same
   * cancellable Node main shutdown lifecycle as the production launcher.
   */
  configureShutdown(port: number, runtimeToken: string, timeoutMs: number): void
  /** Create a native window bound to this Application's event loop. */
  createWindow(opts?: WindowOptions | undefined | null): BrowserWindow
  /**
   * Freeze every native window/WebView declaration before the event loop
   * starts. Runtime commands may subsequently name only these templates.
   */
  configureWindows(templates: Array<RuntimeWindowTemplate>): void
  /** Sugar: create a window + attach a webview in one call. */
  createWebview(windowOpts: WindowOptions | undefined | null, webviewOpts: WebviewOptions): Webview
  /** Run the tao event loop. Blocks the calling thread until quit. */
  run(): void
  onQuit(callback: ((err: Error | null, ) => any)): void
  exit(): void
  /**
   * Set the Dock/About-panel icon at runtime. Packaged apps run under a
   * bundled `node` binary (not a "real" app executable), so `Info.plist`'s
   * `CFBundleIconFile` alone doesn't reliably make the About panel pick up
   * the app icon — this sets `NSApp.applicationIconImage` explicitly.
   * No-op (not an error) if `path` doesn't point at a readable image, or on
   * non-macOS platforms.
   */
  setIconPath(path: string): void
}

export declare class BrowserWindow {
  /**
   * Attach a webview to this window.
   *
   * Hands the webview a clone of the shared window handle so the tao window
   * outlives this `BrowserWindow` — otherwise `Application::createWebview`,
   * which drops its intermediate `BrowserWindow`, would close the NSWindow
   * before the event loop runs.
   */
  createWebview(opts: WebviewOptions): Webview
  setTitle(title: string): void
  setSize(width: number, height: number): void
  minimize(): void
  toggleMaximize(): void
  show(): void
  hide(): void
  focus(): void
  setAlwaysOnTop(enabled: boolean): void
  isVisible(): boolean
  isFocused(): boolean
  isMaximized(): boolean
  isMinimized(): boolean
  close(): void
}

export declare class Webview {
  loadUrl(url: string): void
  loadHtml(html: string): void
  evaluate(js: string): void
  openDevtools(): void
  onIpcMessage(callback: ((err: Error | null, arg: string) => any)): void
  /**
   * **Show a native context menu at the given position.**
   *
   * Public API kept for direct callers; the IPC path (`useGlobalContextMenu`)
   * no longer goes through here and instead calls `show_native_context_menu`
   * directly from the IPC handler — see the module doc comment.
   */
  showContextMenu(menu: MenuOptions, position?: Position | undefined | null): void
  dispose(): void
}

/**
 * `clipboard.readImage`'s result shape — decoded clipboard pixels
 * re-encoded as a PNG and base64-wrapped for the wire (see
 * `clipboard::clipboard_read_image`). Serialize-only: this never crosses the
 * JS -> Rust direction.
 */
export interface ClipboardImageData {
  width: number
  height: number
  pngBase64: string
}

export declare function clipboardRead(): string

export declare function clipboardReadImage(): ClipboardImageData | null

export declare function clipboardWrite(text: string): void

export declare function clipboardWriteHtml(opts: ClipboardWriteHtmlOptions): void

export interface ClipboardWriteHtmlOptions {
  html: string
  altText?: string
}

export declare function clipboardWriteImage(opts: ClipboardWriteImageOptions): void

export interface ClipboardWriteImageOptions {
  pngBase64: string
}

export interface DialogFilter {
  name: string
  extensions: Array<string>
}

/**
 * Also parsed straight out of the IPC JSON payload (`kind: "contextMenu"`)
 * by `webview::handle_ipc_message` — hence the `serde::Deserialize` derive
 * alongside the usual `#[napi(object)]` one. `submenu` is self-recursive
 * and serde handles that automatically.
 */
export interface MenuItemOptions {
  id?: string
  label?: string
  enabled?: boolean
  accelerator?: string
  icon?: string
  separator?: boolean
  submenu?: Array<MenuItemOptions>
  /**
   * Predefined role: 'copy' | 'cut' | 'paste' | 'selectAll' | 'quit' |
   * 'reload' | 'about' | 'toggleFullscreen' | 'services' | 'hide' | ...
   */
  role?: string
}

/**
 * Localized labels for the standard menu bar's items — macOS's
 * `PredefinedMenuItem`s hardcode English, and Windows's custom `MenuItem`s
 * have no localization of their own either, so murasaki resolves per-locale
 * labels in JS (or, for the production launcher, in Rust — see
 * `launcher.rs`'s `shared::resolve_menu_labels`) and passes them through
 * here. Any field left `None` falls back to the English literal.
 */
export interface MenuLabels {
  about?: string
  services?: string
  hideOthers?: string
  hide?: string
  showAll?: string
  quit?: string
  edit?: string
  undo?: string
  redo?: string
  cut?: string
  copy?: string
  paste?: string
  selectAll?: string
  window?: string
  minimize?: string
  zoom?: string
}

export interface MenuOptions {
  items: Array<MenuItemOptions>
}

/**
 * `dialog.showMessage` options. `level` and `buttons` are validated and
 * defaulted (`'info'`/`'ok'`) in `dialog::show_message_dialog` rather than
 * here, so invalid values surface as a normal rejected Promise instead of an
 * N-API argument-conversion panic.
 */
export interface MessageDialogOptions {
  title?: string
  message: string
  level?: string
  buttons?: string
}

export interface NotificationOptions {
  title: string
  body?: string
  icon?: string
  sound?: boolean
}

export declare function openDirectoryDialog(opts?: OpenFileOptions | undefined | null): string | null

export declare function openFileDialog(opts?: OpenFileOptions | undefined | null): Array<string>

export interface OpenFileOptions {
  title?: string
  defaultPath?: string
  filters?: Array<DialogFilter>
  multiple?: boolean
}

export interface Position {
  x: number
  y: number
}

/**
 * Immutable native window template configured before the event loop starts.
 * Runtime create/destroy commands may reference only these labels.
 */
export interface RuntimeWindowTemplate {
  window: WindowOptions
  webview: WebviewOptions
  createOnLaunch: boolean
}

export declare function saveFileDialog(opts?: SaveFileOptions | undefined | null): string | null

export interface SaveFileOptions {
  title?: string
  defaultPath?: string
  defaultName?: string
  filters?: Array<DialogFilter>
}

export declare function shellOpenExternal(target: string): void

export declare function shellShowItemInFolder(path: string): void

/**
 * Blocking, main-thread rfd message box — called synchronously from
 * `handle_native_call` exactly like `open_file_dialog`/`save_file_dialog`
 * above (no spawned thread or channel of its own).
 */
export declare function showMessageDialog(opts: MessageDialogOptions): string

export declare function showNotification(opts: NotificationOptions): string

export declare function version(): string

export interface WebviewOptions {
  url?: string
  html?: string
  devtools?: boolean
  transparent?: boolean
  /**
   * Stable application identifier used to isolate WebView runtime data
   * (notably WebView2 profiles on Windows) between Murasaki applications.
   */
  appId?: string
  /** Complete custom User-Agent value for this WebView. */
  userAgent?: string
  /**
   * Use a non-persistent private browsing session. The WebContext profile
   * is ignored by Wry when enabled.
   */
  incognito?: boolean
  /** Unauthenticated HTTP CONNECT or SOCKSv5 proxy. */
  proxy?: WebviewProxyOptions
  /** Exact renderer-native command permissions. Missing/empty is deny-all. */
  capabilities?: Array<string>
  /**
   * Versioned JSON policy carrying value-level allow/deny scopes. Omitted
   * metadata keeps the legacy permission-name behavior for compatibility.
   */
  capabilityPolicy?: string
  /** Default packaged/development PNG used when creating a tray icon. */
  trayIcon?: string
  /**
   * When set, static files under this directory are served via wry's custom
   * protocol (`murasaki://localhost/…`) instead of `url`/`html` — used in
   * production, where an in-process HTTP server can't work because
   * `Application::run()` blocks Node's event loop. Takes priority over
   * `url`/`html` when set.
   */
  serveDir?: string
}

export interface WebviewProxyOptions {
  protocol: string
  host: string
  port: number
}

export interface WindowOptions {
  /**
   * Stable label used by cross-window APIs. `main` is reserved for the
   * primary window.
   */
  label?: string
  /**
   * Whether this is the primary application window. Defaults to true only
   * for the reserved `main` label.
   */
  primary?: boolean
  /** Initial visibility. Defaults to true. */
  visible?: boolean
  title?: string
  width?: number
  height?: number
  minWidth?: number
  minHeight?: number
  resizable?: boolean
  transparent?: boolean
  /** macOS only. Values: 'hud' | 'sidebar' | 'popover' | 'window-background' | null */
  vibrancy?: string
  /**
   * macOS only. Resolved path to a PNG icon used for the standard "About
   * <app>" panel (`NSAboutPanelOptionApplicationIcon`). Does not affect the
   * Dock icon — see `Application::setIconPath` for that.
   */
  icon?: string
  /** Populates the "Version" field of the native "About <app>" panel. */
  version?: string
  /** Populates the description field of the native "About <app>" panel. */
  description?: string
  /** Populates the copyright field of the native "About <app>" panel. */
  copyright?: string
  /** Populates the homepage/website field of the native "About <app>" panel. */
  homepage?: string
  /** Populates the authors field of the native "About <app>" panel. */
  authors?: Array<string>
  /**
   * Localized labels for the standard menu bar — macOS's App/Edit/Window
   * (see `crate::menu::build_default_app_menu`) and Windows's File/Edit/Window
   * (see `crate::menu::build_windows_menu_bar`). Falls back to English when
   * absent. Unused on Linux (no default menu bar there yet).
   */
  menuLabels?: MenuLabels
}
