/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Application {
  constructor()
  /** Create a native window bound to this Application's event loop. */
  createWindow(opts?: WindowOptions | undefined | null): BrowserWindow
  /** Sugar: create a window + attach a webview in one call. */
  createWebview(windowOpts: WindowOptions | undefined | null, webviewOpts: WebviewOptions): Webview
  /** Run the tao event loop. Blocks the calling thread until quit. */
  run(): void
  onQuit(callback: ((err: Error | null, ) => any)): void
  exit(): void
  /**
   * Set the Dock/About-panel icon at runtime. Packaged apps run under a
   * bundled `node` binary (not a "real" app executable), so `Info.plist`'s
   * `CFBundleIconFile` alone doesn't reliably make the About panel pick up
   * the app icon — this sets `NSApp.applicationIconImage` explicitly.
   * No-op (not an error) if `path` doesn't point at a readable image, or on
   * non-macOS platforms.
   */
  setIconPath(path: string): void
}

export declare class BrowserWindow {
  /**
   * Attach a webview to this window.
   *
   * Hands the webview a clone of the shared window handle so the tao window
   * outlives this `BrowserWindow` — otherwise `Application::createWebview`,
   * which drops its intermediate `BrowserWindow`, would close the NSWindow
   * before the event loop runs.
   */
  createWebview(opts: WebviewOptions): Webview
  setTitle(title: string): void
  setSize(width: number, height: number): void
  minimize(): void
  toggleMaximize(): void
  close(): void
}

export declare class Webview {
  loadUrl(url: string): void
  loadHtml(html: string): void
  evaluate(js: string): void
  openDevtools(): void
  onIpcMessage(callback: ((err: Error | null, arg: string) => any)): void
  /**
   * **Show a native context menu at the given position.**
   *
   * Public API kept for direct callers; the IPC path (`useGlobalContextMenu`)
   * no longer goes through here and instead calls `show_native_context_menu`
   * directly from the IPC handler — see the module doc comment.
   */
  showContextMenu(menu: MenuOptions, position?: Position | undefined | null): void
  dispose(): void
}

export declare function clipboardRead(): string

export declare function clipboardWrite(text: string): void

export interface DialogFilter {
  name: string
  extensions: Array<string>
}

/**
 * Also parsed straight out of the IPC JSON payload (`kind: "contextMenu"`)
 * by `webview::handle_ipc_message` — hence the `serde::Deserialize` derive
 * alongside the usual `#[napi(object)]` one. `submenu` is self-recursive
 * and serde handles that automatically.
 */
export interface MenuItemOptions {
  id?: string
  label?: string
  enabled?: boolean
  accelerator?: string
  icon?: string
  separator?: boolean
  submenu?: Array<MenuItemOptions>
  /**
   * Predefined role: 'copy' | 'cut' | 'paste' | 'selectAll' | 'quit' |
   * 'reload' | 'about' | 'toggleFullscreen' | 'services' | 'hide' | ...
   */
  role?: string
}

/**
 * macOS only. Localized labels for the predefined items in the standard
 * application menu bar — muda hardcodes English for these, so murasaki
 * resolves per-locale labels in JS and passes them through here. Any field
 * left `None` falls back to muda's English default.
 */
export interface MenuLabels {
  about?: string
  services?: string
  hideOthers?: string
  hide?: string
  showAll?: string
  quit?: string
  edit?: string
  undo?: string
  redo?: string
  cut?: string
  copy?: string
  paste?: string
  selectAll?: string
  window?: string
  minimize?: string
  zoom?: string
}

export interface MenuOptions {
  items: Array<MenuItemOptions>
}

export interface NotificationOptions {
  title: string
  body?: string
  icon?: string
  sound?: boolean
}

export declare function openDirectoryDialog(opts?: OpenFileOptions | undefined | null): string | null

export declare function openFileDialog(opts?: OpenFileOptions | undefined | null): Array<string>

export interface OpenFileOptions {
  title?: string
  defaultPath?: string
  filters?: Array<DialogFilter>
  multiple?: boolean
}

export interface Position {
  x: number
  y: number
}

export declare function saveFileDialog(opts?: SaveFileOptions | undefined | null): string | null

export interface SaveFileOptions {
  title?: string
  defaultPath?: string
  defaultName?: string
  filters?: Array<DialogFilter>
}

export declare function shellOpenExternal(target: string): void

export declare function shellShowItemInFolder(path: string): void

export declare function showNotification(opts: NotificationOptions): void

export declare function version(): string

export interface WebviewOptions {
  url?: string
  html?: string
  devtools?: boolean
  transparent?: boolean
  /**
   * When set, static files under this directory are served via wry's custom
   * protocol (`murasaki://localhost/…`) instead of `url`/`html` — used in
   * production, where an in-process HTTP server can't work because
   * `Application::run()` blocks Node's event loop. Takes priority over
   * `url`/`html` when set.
   */
  serveDir?: string
}

export interface WindowOptions {
  title?: string
  width?: number
  height?: number
  minWidth?: number
  minHeight?: number
  resizable?: boolean
  transparent?: boolean
  /** macOS only. Values: 'hud' | 'sidebar' | 'popover' | 'window-background' | null */
  vibrancy?: string
  /**
   * macOS only. Resolved path to a PNG icon used for the standard "About
   * <app>" panel (`NSAboutPanelOptionApplicationIcon`). Does not affect the
   * Dock icon — see `Application::setIconPath` for that.
   */
  icon?: string
  /** Populates the "Version" field of the native "About <app>" panel. */
  version?: string
  /** Populates the description field of the native "About <app>" panel. */
  description?: string
  /** Populates the copyright field of the native "About <app>" panel. */
  copyright?: string
  /** Populates the homepage/website field of the native "About <app>" panel. */
  homepage?: string
  /** Populates the authors field of the native "About <app>" panel. */
  authors?: Array<string>
  /**
   * macOS only. Localized labels for the standard App/Edit/Window menu bar
   * (see `crate::menu::build_default_app_menu`). Falls back to English when
   * absent.
   */
  menuLabels?: MenuLabels
}
